# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_pagecrawl_page_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecrawl',
            name='id',
        ),
        migrations.AlterField(
            model_name='pagecrawl',
            name='page_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
