# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20171029_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchitem',
            old_name='detail',
            new_name='title',
        ),
    ]
