# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_searchitem_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecrawl',
            name='logo',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchitem',
            name='detail',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchitem',
            name='item_link',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchitem',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
