# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20171102_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchitem',
            name='URLstrip',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
