# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_searchitem_urlstrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchitem',
            name='id',
        ),
        migrations.AddField(
            model_name='searchitem',
            name='item_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
